######################################################################
# Automatically generated by qmake (3.0) Fri Apr 17 13:58:00 2015
######################################################################

TEMPLATE = app
TARGET = p6profiler-qt
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += RoutineListModel.h ProfilingDataParser.h RoutineView.h
SOURCES += main.cpp RoutineListModel.cpp ProfilingDataParser.cpp RoutineView.cpp
    
